version: '3.8'

services:
  docker_local_registry:
    image: registry:2
    volumes:
    - registry_data:/var/lib/registry
    networks:
    - docker_swarm_public
    deploy:
        mode: replicated
        replicas: 1
        placement:
          constraints: [node.role == manager]
        labels:
        - "traefik.enable=true"
        - "traefik.http.services.portainer.loadbalancer.server.port=5000" # it seems you always need to give traefik a port so it 'notices' the service  
        - "traefik.http.routers.portainer.entrypoints=websecure"
        - "traefik.http.routers.portainer.rule=Host(`docker.nokwebspace.ovh`)"
        - "traefik.docker.network=docker_swarm_public"

volumes:
    registry_data:

networks: 
    docker_swarm_public:
        external: true