version: '3.8'

services:
  traefik:
    volumes:
      # So that Traefik can listen to the Docker events
      - C:\Users\coued\Projects\OR\OR_NETWORK-AND-DISCRETE-LOCATION\Environnements\ansible-playbook\traefik\local\traefik.yml:/etc/traefik/traefik.yml
      - C:\Users\coued\Projects\OR\OR_NETWORK-AND-DISCRETE-LOCATION\Environnements\ansible-playbook\traefik\local\traefik.log:/traefik.log
      - C:\Users\coued\Projects\OR\OR_NETWORK-AND-DISCRETE-LOCATION\Environnements\ansible-playbook\traefik\local\traefik-access.log:/traefik-access.log

  whoami:
    deploy:
        labels:
          - "traefik.http.routers.whoami.rule=Host(`whoami.dev.nokwebspace.ovh`)"