version: '3'

services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.2
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/data/traefik/traefik.yml:/etc/traefik/traefik.yml
      - /var/data/traefik/traefik.log:/traefik.log
      - /var/data/traefik/traefik-access.log:/traefik-access.log
      - /var/data/traefik/acme.json:/acme.json

  whoami:
    # A container that exposes an API to show its IP address
    image: containous/whoami