#################################################
# OR INFRA Playbooks: Traefik
# Source: 
#    https://github.com/arillso/ansible.traefik
#    https://geek-cookbook.funkypenguin.co.nz/ha-docker-swarm/traefik/
#################################################
---
- hosts: swarm_managers
  gather_facts: no
  become: true
  vars_files:
    - vars/ovh_application.vault.yml
    - vars/google_oauth.vault.yml
  vars:  
    traefik_dir: "/var/data/traefik"
    traefik_config_template: secure
  tasks:
    ###
    # The stack cannot be up while updating secrets
    ###
    - name: Remove Traefik stack
      docker_stack:
        name: traefik
        state: absent

    ###
    # Google Auth Setup
    ###
    - name: Create FORWARD_AUTH secret (from a file on the control machine)
      docker_secret:
        name: "TRAEFIK_FORWARD_AUTH_PROVIDERS_GOOGLE"
        data: "{{ lookup('file', playbook_dir + '/TRAEFIK_FORWARD_AUTH_PROVIDERS_GOOGLE.env') }}"
        force: yes
        state: present

    - name: Create DNS API secret (from a file on the control machine)
      docker_secret:
        name: "{{ item }}"
        data: "{{ lookup('vars', 'vault_' + item)}}"
        force: yes
        state: present
      with_items:
      - "OVH_ENDPOINT"
      - "OVH_APPLICATION_KEY"
      - "OVH_APPLICATION_SECRET"
      - "OVH_CONSUMER_KEY"