version: '3.3'

services:
    mongodb:
        image: mongo
        volumes:
           - db-data:/data/db
        networks: 
        - jupyterhub_jupyterhub_network
        deploy:
            mode: replicated
            replicas: 1

    mongoclient:
        image: mongoclient/mongoclient
        hostname: mongoclient
        environment: 
            MONGOCLIENT_DEFAULT_CONNECTION_URL: mongodb://mongodb:27017/NETWORK-AND-DISCRETE-LOCATION
        depends_on:
        - mongodb
        networks:
        - docker_swarm_public
        deploy:
            mode: replicated
            replicas: 1
            labels:
                - "traefik.enable=true"
                - "traefik.http.services.mongoclient.loadbalancer.server.port=3300" # it seems you always need to give traefik a port so it 'notices' the service  
                - "traefik.http.routers.mongoclient.entrypoints=websecure"
                - "traefik.http.routers.mongoclient.rule=Host(`mongoclient.nokwebspace.ovh`)"
        
volumes:
    db-data:

networks: 
    docker_swarm_public:
        external: true
    jupyterhub_jupyterhub_network:
        external: true
