#################################################
# OR INFRA Playbooks: Docker
# Source: https://docs.docker.com/install/linux/docker-ce/debian/
#################################################
---
    - hosts: all
      become: true
      vars_files:
        - vars/default.yml
    
      tasks:
        - name: Install aptitude using apt
          apt: name=aptitude state=latest update_cache=yes force_apt_get=yes
    
        - name: Install required system packages
          apt: name={{ item }} state=latest update_cache=yes
          loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']
    
        - name: Add Docker GPG apt Key
          apt_key:
            url: https://download.docker.com/linux/debian/gpg
            state: present
    
        - name: Add Docker Repository
          apt_repository:
            repo: deb [arch=amd64] https://download.docker.com/linux/debian buster stable
            state: present
    
        - name: Update apt and install docker-ce
          apt: name={{ item }} state=latest update_cache=yes
          loop: ['docker-ce', 'docker-ce-cli', 'docker-compose', 'containerd.io']
  
        - name: Install Docker Module for Python
          pip:
            executable: pip3
            name: docker
    
###
# Testing Setup
###
        - name: Pull default Docker image for testing
          docker_image:
            name: "hello-world"
            source: pull
    
        - name: Create default containers
          docker_container:
            name: "hello-world"
            image: "hello-world"
            state: present

        - name: Stop a container
          docker_container:
            name: "hello-world"
            state: stopped